[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = [
  "bun run typecheck"
]

[start]
cmd = "bun src/server/index.ts"

[variables]
NODE_ENV = "production"
